### ISSUE TITLE
Punching - high aspect ratio columns

### ISSUE THREAD

**Issue by mikegatt** [MagmaWorks/SCaFFOLD#40]
I've read up on some technical advice in TR64 regarding high aspect ratio columns in flat slabs. The recommendation on page 51 seems to be to take the maximum column dimension in the perimeter calculation as 3d.

![image](https://user-images.githubusercontent.com/41989318/71783413-5a276d80-2fde-11ea-8441-258e4a6cd479.png)

This seems to limit u1/u1* and the value of beta to take in calculation. This seems to be a good way to resolve the issue we were encountering with very high values of beta making longer columns worse than shorter columns for punching shear

**Comment by AlBal2** [comment]
Yes, that would limit u1/u1* and prevent the beta value running away for long columns. I'll update the calc to suit.

**Comment by AlBal2** [comment]
Implemented and deployed 14/4/2020 (in v 0.4.5)
